### PR TITLE
Fix 4 accounts limit, upgrade dependencies, remove bootstrap, dark-mode

### PR DESCRIPTION
**Pull request by uplg**
Hi ! Thanks for that. Allowed me to migrate from Google Authenticator to Authy really easily.

I upgraded dependencies, removed bootstrap and styled a bit by hand ^^

Also, replaced `jsqr` by `qr-scanner` to allow "big" exports QR Code (> 4 accounts)

Result : https://ga.mimisiku.dev/

PRRender

Gn!

### CODE REVIEW

**Comment by uplg** [comment]
Don't really know if that repository is active, but I hosted the PR on a sub-domain ;)

https://ga.mimisiku.dev/

**Comment by kiehnek** [comment]
Thanks for your PR! 

I tested it on your site and it seems like the file upload isn't working. I'm not really a fan of the material design, but I understand the need for a dark mode. I was not able to reproduce your problem with `jsQR`.

**Comment by uplg** [comment]
Oh yep, bad CSP policy, but it should work locally. (Fixed)

That's really strange that you aren't able to reproduce. Try export and select all of your accounts.

For Material, it's just better than before, but I can remove it haha

**Comment by kiehnek** [comment]
I exported all my accounts and all of them were listed.

Can you send me a dummy QR code with made up accounts and random secrets to reproduce the issue?

**Comment by kiehnek** [comment]
As for the design I don't think there really is an objective better or worse option as it just comes down to personal taste.

**Comment by uplg** [comment]
Will try to send you a dummy QR.

If you don't want to merge that's fine ^^

**Comment by kiehnek** [comment]
I'll close this for now as I cannot reproduce our issue.

**Pull request closed without merging**
